"""initial schema

Revision ID: 904a80d53212
Revises: 
Create Date: 2026-07-02 17:17:50.091847
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '904a80d53212'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_runs_idempotency_key'), 'catalog_runs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_catalog_runs_status'), 'catalog_runs', ['status'], unique=False)
    op.create_table('catalog_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('sku', sa.String(length=32), nullable=False),
    sa.Column('source_title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('attributes', sa.Text(), nullable=False),
    sa.Column('listing_title', sa.String(length=80), nullable=True),
    sa.Column('selling_points', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=False),
    sa.Column('draft_source', sa.String(length=32), nullable=True),
    sa.Column('workflow_version', sa.String(length=64), nullable=True),
    sa.Column('draft_attempts', sa.Integer(), nullable=False),
    sa.Column('erp_record_id', sa.String(length=128), nullable=True),
    sa.Column('erp_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['catalog_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_items_run_id'), 'catalog_items', ['run_id'], unique=False)
    op.create_index(op.f('ix_catalog_items_sku'), 'catalog_items', ['sku'], unique=False)
    op.create_index(op.f('ix_catalog_items_status'), 'catalog_items', ['status'], unique=False)
    op.create_table('erp_operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('operation_key', sa.String(length=128), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['catalog_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_operations_operation_key'), 'erp_operations', ['operation_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_erp_operations_operation_key'), table_name='erp_operations')
    op.drop_table('erp_operations')
    op.drop_index(op.f('ix_catalog_items_status'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_sku'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_run_id'), table_name='catalog_items')
    op.drop_table('catalog_items')
    op.drop_index(op.f('ix_catalog_runs_status'), table_name='catalog_runs')
    op.drop_index(op.f('ix_catalog_runs_idempotency_key'), table_name='catalog_runs')
    op.drop_table('catalog_runs')
    # ### end Alembic commands ###
