"""initial_schema

Revision ID: 979e40f9a3dc
Revises: 
Create Date: 2026-07-01 15:58:53.634742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '979e40f9a3dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue_clusters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('trend', sa.String(length=16), nullable=False),
    sa.Column('suggested_owner', sa.String(length=32), nullable=False),
    sa.Column('centroid', sa.JSON(), nullable=False),
    sa.Column('representative_ticket_ids', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('week_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_start')
    )
    op.create_table('sop_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cluster_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['issue_clusters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('user_type', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_status', sa.String(length=32), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['demo_sessions.id'], ),  # noqa: S1192 (migration - frozen schema snapshot)
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'external_id', name='uq_session_ticket')
    )
    op.create_index(op.f('ix_tickets_external_id'), 'tickets', ['external_id'], unique=False)
    op.create_index(op.f('ix_tickets_input_hash'), 'tickets', ['input_hash'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('problem_type', sa.String(length=32), nullable=False),
    sa.Column('product_area', sa.String(length=32), nullable=False),
    sa.Column('suggested_owner', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('needs_escalation', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('workflow_version', sa.String(length=64), nullable=False),
    sa.Column('analysis_source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),  # noqa: S1192 (migration - frozen schema snapshot)
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_problem_type'), 'analyses', ['problem_type'], unique=False)
    op.create_index(op.f('ix_analyses_product_area'), 'analyses', ['product_area'], unique=False)
    op.create_index(op.f('ix_analyses_review_status'), 'analyses', ['review_status'], unique=False)
    op.create_index(op.f('ix_analyses_severity'), 'analyses', ['severity'], unique=False)
    op.create_index(op.f('ix_analyses_suggested_owner'), 'analyses', ['suggested_owner'], unique=False)
    op.create_index(op.f('ix_analyses_ticket_id'), 'analyses', ['ticket_id'], unique=True)
    op.create_table('analysis_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),  # noqa: S1192 (migration - frozen schema snapshot)
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_status'), 'analysis_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_ticket_id'), 'analysis_jobs', ['ticket_id'], unique=False)
    op.create_table('cluster_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cluster_id', sa.String(length=36), nullable=False),
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['issue_clusters.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),  # noqa: S1192 (migration - frozen schema snapshot)
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'ticket_id', name='uq_cluster_member')
    )
    op.create_index(op.f('ix_cluster_members_cluster_id'), 'cluster_members', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_cluster_members_ticket_id'), 'cluster_members', ['ticket_id'], unique=False)
    op.create_table('sop_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['sop_candidates.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['demo_sessions.id'], ),  # noqa: S1192 (migration - frozen schema snapshot)
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'candidate_id', name='uq_sop_review')
    )
    op.create_index(op.f('ix_sop_reviews_candidate_id'), 'sop_reviews', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_sop_reviews_session_id'), 'sop_reviews', ['session_id'], unique=False)
    op.create_table('ticket_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('corrections', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['demo_sessions.id'], ),  # noqa: S1192 (migration - frozen schema snapshot)
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),  # noqa: S1192 (migration - frozen schema snapshot)
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'ticket_id', name='uq_session_review')
    )
    op.create_index(op.f('ix_ticket_reviews_session_id'), 'ticket_reviews', ['session_id'], unique=False)
    op.create_index(op.f('ix_ticket_reviews_ticket_id'), 'ticket_reviews', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_reviews_ticket_id'), table_name='ticket_reviews')
    op.drop_index(op.f('ix_ticket_reviews_session_id'), table_name='ticket_reviews')
    op.drop_table('ticket_reviews')
    op.drop_index(op.f('ix_sop_reviews_session_id'), table_name='sop_reviews')
    op.drop_index(op.f('ix_sop_reviews_candidate_id'), table_name='sop_reviews')
    op.drop_table('sop_reviews')
    op.drop_index(op.f('ix_cluster_members_ticket_id'), table_name='cluster_members')
    op.drop_index(op.f('ix_cluster_members_cluster_id'), table_name='cluster_members')
    op.drop_table('cluster_members')
    op.drop_index(op.f('ix_analysis_jobs_ticket_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_status'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index(op.f('ix_analyses_ticket_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_suggested_owner'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_severity'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_review_status'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_product_area'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_problem_type'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_tickets_input_hash'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_external_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('sop_candidates')
    op.drop_table('weekly_reports')
    op.drop_table('issue_clusters')
    op.drop_table('demo_sessions')
    # ### end Alembic commands ###
